kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry:5000"]
      endpoint = ["http://registry:5000"]

  # this previous step actually creates a local docker registry
nodes:
- role: control-plane
  extraPortMappings:
    - containerPort: 81
      hostPort: 81
      listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
      protocol: udp # Optional, defaults to tcp
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "has-cpu=true"
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "has-gpu=true"

  